services:
  - type: web
    name: dice-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
  - key: DATABASE_URL
    value: postgresql://postgres:12345abC_MatKhau@db.yqtvaxgthwqjegjouxko.supabase.co:5432/postgres?sslmode=require
